# fly.toml app configuration file generated for essaygenius-frontend-black-pine-2721 on 2025-04-12T22:31:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'essaygenius'
primary_region = 'ord'

[build.args]
  NEXT_PUBLIC_API_URL = "https://essay-gen.fly.dev"
  NEXT_PUBLIC_SUPABASE_URL = "https://ileodcwfpitqeirwshly.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZW9kY3dmcGl0cWVpcndzaGx5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwMDA4NjYsImV4cCI6MjA1OTU3Njg2Nn0.teY75Ud405VmYBInZs3uPL56jxxL42-eAwikXaM2PJA"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
