# fly.toml app configuration file generated for essaygenius-backend on 2025-04-12T22:22:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'essay-gen'
primary_region = 'ord'

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
